### ISSUE TITLE
food4rhino

### ISSUE THREAD

**Issue by KalipheGTU** [Esri/puma#37]
hi
we can't find it in food4rhino?

**Comment by mistafunk** [comment]
Puma is not yet on food4rhino. We will put it there a soon as we have 1.0 (currently producing demo video and examples). The current release is 0.9.4 and you can download the `rhi` here: https://github.com/Esri/puma/releases/tag/v0.9.4

**Comment by KalipheGTU** [comment]
Thank you for the answer
